- hosts: localhost
  gather_facts: no
  connection: local
  vars:
  - auto_commit: True
  - manageiq_validate_certs: False
  - templates: []
  - template_dialog: {}
  roles:
  - syncrou.manageiq-automate
  tasks:
    - name: Gather only registered virtual machine templates
      vmware_vm_facts:
        hostname: vcenter-aa11.rhpds.opentlc.com
        username: root
        password: r3dh4t1!
        vm_type: template
        validate_certs: false
      delegate_to: localhost
      register: template_facts

    - name: print gather_facts
      debug:
       msg: "{{template_facts.virtual_machines.keys()}}"

    - name: create templates lists
      set_fact:
        templates: "{{templates + [{item: item}]}}"
      with_items: "{{template_facts.virtual_machines.keys()}}"

    - name: create templates dialog
      set_fact:
        template_dialog:
          values: "{{templates}}"
          data_type: string
          sort_by: value
          default_value: 123

    - name: "Set a State Var"
      manageiq_automate:
        workspace: "{{ workspace }}"
        set_attribute:
          object: "root"
          attribute: dialog_dropdown_list_1_1
          value : "{{template_dialog}}"
      register: workspace

    - name: print workspace
      debug:
        msg: "{{workspace}}"

    - name: print
      debug:
        msg: "{{hostvars[inventory_hostname]}}"

    - name: "Set a State Var"
      manageiq_automate:
        workspace: "{{ workspace }}"
        set_state_var:
          attribute: "job_id"
          value: "xyz"
      register: workspace
