- hosts: localhost
  vars:
    list: ["t1", "t2", "t3"]
    template_dialog: {}
    templates: []
  tasks:
    - name: create lists
      set_fact:
        templates: "{{templates + [{item: item}]}}"
      with_items: "{{list}}"

    - name: create dialg dict
      set_fact:
        template_dialog:
          values: "{{templates}}"
    - name: print templates
      debug:
        msg: "{{template_dialog}}"
