- hosts: localhost
  connection: local

- import_playbook: rhv_basic_provisioning.yml
  when: provider| lower | search("rhv")
- include: vmware_basic_provisioning.yml
  when: provider| lower | search("vsphere")
