---
- name: rhv_basic_provisioning
  hosts: localhost
  gather_facts: false
  vars:
    vm_names: ["vm1"]
    template: cfmer-template
    datacenter: CoolDataCenter
    cluster: TrustedCluster
    network_0_vlan: ovirtmgmt
    ovirt_user: "admin@internal"
    ovirt_pass: "r3dh4t1!"
    ovirt_host:  "rhvm-aa11.rhpds.opentlc.com"

  pre_tasks:
    - name: authenticate to enging
      ovirt_auth:
        username: '{{ ovirt_user }}'
        password: '{{ ovirt_pass }}'
        url: https://{{ ovirt_host }}/ovirt-engine/api
        insecure: true
  roles:
    - role: rhv_preprovision
      when: manageiq is defined

    - role: rhv_vmname

    - role: rhv_basic_provision

    - role: rhv_postprovision
      when: rhv_created_vms is defined and manageiq is defined

- name: Perform tasks on instances
  hosts: rhv_hosts
  vars:
    ansible_ssh_user: root
    ansible_ssh_pass: "123"
  roles:
    - role: rhv_runonce
