---
# For a full list of vmware_guest parameters, visit:
# http://docs.ansible.com/ansible/latest/vmware_guest_module.html

# vcenter parameters
validate_certs: false
template:
datacenter:
cluster:
storage:
folder: "/vm/Discovered virtual machine"

# vm guest parameters
vm_names:
vm_ips: []
vms_specs: {}
memory_mb: 1024
num_cpus: 1
notes: Provisioned via Ansible
state: poweredon
wait_for_ip_address: true


## vm networking parameters
nics:
  - name: "eth0"
    profile_name: "{{ network_0_vlan | default('ovirtmgmt') }}"

    ### static network parameters
    # ip: "{{ network_0_ip | default(omit, true) }}"
    # netmask: "{{ network_0_netmask | default(omit, true) }}"
    # gateway: "{{ network_0_gateway | default(omit, true) }}"
    # mac: "{{ network_0_mac | default(omit, true) }}"
    # domain: "{{ network_0_dnsdomain | default(omit, true) }}"
    # dns_servers:
    #   - "{{ network_0_dns_0_server | default(omit, true) }}"
    #   - "{{ network_0_dns_1_server | default(omit, true) }}"

## vm disk parameters
# disks:
#   - size_gb: "{{ vm_disk_0_size_gb }}"
#     type: "{{ vm_disk_0_type | default('thin') }}"
#     datastore: "{{ vm_disk_0_datastore }}"
#   - size_gb: "{{ vm_disk_1_size_gb }}"
#     type: "{{ vm_disk_1_type | default('thin') }}"
#     datastore: "{{ vm_disk_1datastore }}"

## vm customization parameters
# customizations:

## vm linked clone parameter
snapshot_src:
linked_clone: false

# asynchronous parameters
async_wait: 3600
async_poll: 0
async_retries: 100

# enable extra debugging
verbose: false
